sources:
  - ElMessiri.glyphs
axisOrder:
  - wght
familyName: "El Messiri"
stat:
  ElMessiri[wght].ttf:
  - name: Weight
    tag: wght
    values:
    - name: Regular
      value: 400
      linkedValue: 700
      flags: 2
    - name: Medium
      value: 500
    - name: SemiBold
      value: 600
    - name: Bold
      value: 700